/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dr.Abuzant
 */
public class ChatInterface extends javax.swing.JFrame {

    /**
     * Creates new form ChatInterface
     */
    public ChatInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        sendprt = new javax.swing.JTextField();
        set = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageContainer = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        message = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rec = new javax.swing.JTextField();
        Dest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        All = new javax.swing.JRadioButton();
        First = new javax.swing.JRadioButton();
        Second = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("sendPort");

        sendprt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendprtActionPerformed(evt);
            }
        });

        set.setText("set");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });

        MessageContainer.setEditable(false);
        MessageContainer.setColumns(20);
        MessageContainer.setRows(5);
        jScrollPane1.setViewportView(MessageContainer);

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        jLabel2.setText("recievePort");

        jLabel3.setText("Destination");

        buttonGroup2.add(All);
        All.setSelected(true);
        All.setText("ALL");

        buttonGroup2.add(First);
        First.setText("First");
        First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstActionPerformed(evt);
            }
        });

        buttonGroup2.add(Second);
        Second.setText("Second");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Dest)
                                .addComponent(rec)
                                .addComponent(sendprt, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                            .addComponent(All)
                            .addComponent(First)
                            .addComponent(Second))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message)
                        .addGap(18, 18, 18)
                        .addComponent(send)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sendprt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set)
                        .addGap(18, 18, 18)
                        .addComponent(All)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(First)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Second)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
       int port = Integer.parseInt(rec.getText());
    int client =Integer.parseInt(sendprt.getText());
     sendprt.setEnabled(false);
     rec.setEnabled(false);
     Dest.setEnabled(false);
    set.setEnabled(false);
        startServer(port,client);
    }//GEN-LAST:event_setActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try {
            // TODO add your handling code here:
            int port =Integer.parseInt(sendprt.getText());
            String messages = message.getText();
            String m[]=Dest.getText().split(",");
//               int dest = Integer.parseInt(dst.getText());
            startSender(port,messages,m);
        } catch (UnknownHostException ex) {
            Logger.getLogger(ChatInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendActionPerformed

    private void sendprtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendprtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendprtActionPerformed

    private void FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatInterface().setVisible(true);
            }
        });
    }
    
  public static void startServer(int port, int dest ) {
    (new Thread() {
        @Override
        public void run() {
            try {
                DatagramSocket serverSocket = new DatagramSocket(port);
                
                byte[] receiveData = new byte[1024];
                byte[] sendData  = new byte[1024];
                
                while(true)
                {
                    Arrays.fill(receiveData,(byte)0);
                    Arrays.fill(sendData,(byte)0);
                    DatagramPacket receivePacket =
                            new DatagramPacket(receiveData, receiveData.length);
                    serverSocket.receive(receivePacket);
                    String sentence = new String(receivePacket.getData());
                    
                    InetAddress IPAddress = receivePacket.getAddress();
                    
                    
                     
                    
                    sendData = sentence.getBytes();
                    MessageContainer.append(sentence +"\n");
                    DatagramPacket sendPacket =
                            new DatagramPacket(sendData, sendData.length, IPAddress,
                                    dest);
                    
                    serverSocket.send(sendPacket); 
                }   } catch (SocketException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            }

           
        }
    }).start();
  }

  public static void startSender(int port, String message,String[] destination) throws UnknownHostException{
   
    (new Thread() {
        @Override
        public void run() {
            try { 
                DatagramSocket clientSocket = new DatagramSocket(port); 
                InetAddress IPAddress = InetAddress.getByName("localhost");
          
  
      byte[] sendData = new byte[1024]; 
      byte[] receiveData = new byte[1024]; 
  String sentence= message;
   MessageContainer.append("me: "+sentence +"\n");
   sentence= port+": "+sentence;
      sendData = sentence.getBytes();   
      if(All.isSelected()){
          
      
      for(int i=0;i<2;i++){
            DatagramPacket sendPacket = 
         new DatagramPacket(sendData, sendData.length, IPAddress, Integer.parseInt(destination[i])); 
  
      clientSocket.send(sendPacket); 
  
      }
      }
      else if(First.isSelected()){
          
            DatagramPacket sendPacket = 
         new DatagramPacket(sendData, sendData.length, IPAddress, Integer.parseInt(destination[0])); 
  
      clientSocket.send(sendPacket); 
      }
      else{
            DatagramPacket sendPacket = 
         new DatagramPacket(sendData, sendData.length, IPAddress, Integer.parseInt(destination[1])); 
  
      clientSocket.send(sendPacket); 
      }
      clientSocket.close();
      
            } catch (SocketException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnknownHostException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            }
  
            
               

        }}).start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JRadioButton All;
    private javax.swing.JTextField Dest;
    private static javax.swing.JRadioButton First;
    public static javax.swing.JTextArea MessageContainer;
    private static javax.swing.JRadioButton Second;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message;
    private javax.swing.JTextField rec;
    private javax.swing.JButton send;
    private javax.swing.JTextField sendprt;
    private javax.swing.JButton set;
    // End of variables declaration//GEN-END:variables
}
