/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dr.Abuzant
 */
public class ChatInterface extends javax.swing.JFrame {

    /**
     * Creates new form ChatInterface
     */
    public ChatInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        set = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageContainer = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        message = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rec = new javax.swing.JTextField();
        Dest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        All = new javax.swing.JRadioButton();
        First = new javax.swing.JRadioButton();
        Second = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        IP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        set.setText("set");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });

        MessageContainer.setEditable(false);
        MessageContainer.setColumns(20);
        MessageContainer.setRows(5);
        jScrollPane1.setViewportView(MessageContainer);

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        jLabel2.setText("recievePort");

        jLabel3.setText("Destination");

        buttonGroup2.add(All);
        All.setSelected(true);
        All.setText("ALL");

        buttonGroup2.add(First);
        First.setText("First");
        First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstActionPerformed(evt);
            }
        });

        buttonGroup2.add(Second);
        Second.setText("Second");

        jLabel4.setText("IP address");

        jLabel5.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(set, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(Dest)
                                    .addComponent(rec)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(All)
                                    .addComponent(First)
                                    .addComponent(Second)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(154, 154, 154))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(9, 9, 9)
                                        .addComponent(IP))
                                    .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(message)
                        .addGap(18, 18, 18)
                        .addComponent(send)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(set)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(All)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(First)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Second)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
       int port = Integer.parseInt(rec.getText());
    
    
     rec.setEnabled(false);
     Dest.setEnabled(false);
    set.setEnabled(false);
    Name.setEnabled(false);
    IP.setEnabled(false);
        startServer(port);
    }//GEN-LAST:event_setActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        try {
            // TODO add your handling code here:
           
            String messages = message.getText();
            String m[]=Dest.getText().split(",");
            message.setText("");
            startClient(messages,m);
        } catch (UnknownHostException ex) {
            Logger.getLogger(ChatInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendActionPerformed

    private void FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatInterface().setVisible(true);
            }
        });
    }
    
  public static void startServer(int port ) {
    (new Thread() {
        @Override
        public void run() {
            try {
                DatagramSocket serverSocket = new DatagramSocket(port);//starting a server socket with the port number
                
                byte[] receiveData = new byte[1024];//array of bytes to recieveData
                byte[] sendData  = new byte[1024];//arrray of bytes to sendData
                
                while(true)//infinite loop to keep recieving requests
                {
                    Arrays.fill(receiveData,(byte)0);//filling the array with empty string in order to git rid of  data from the previous message
                    Arrays.fill(sendData,(byte)0);//filling the array with empty string in order to git rid of  data from the previous message
                    DatagramPacket receivePacket =
                            new DatagramPacket(receiveData, receiveData.length);// creating a recieve packet to recive data 
                    serverSocket.receive(receivePacket);// recive the data function
                    String sentence = new String(receivePacket.getData());//get the the message text
                    
                    InetAddress IPAddress = receivePacket.getAddress();// get the ip address of the client that send the packet
                    sendData = sentence.getBytes(); // prepare data to be send as bytes
                    MessageContainer.append(sentence +"\n");// display data to MessageContainer
   
                }   } catch (SocketException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            }

           
        }
    }).start();
  }

  public static void startClient(String message,String[] destination) throws UnknownHostException{
   
    (new Thread() {
        @Override
        public void run() {
            try { 
                DatagramSocket clientSocket = new DatagramSocket(); //creating socket for client
                InetAddress IPAddress = InetAddress.getByName(IP.getText());// getting the IP address through Jtextfield
          
  
      byte[] sendData = new byte[1024]; //array of bytes for the sent data
     
  String sentence= message;//store message from jtextfield to sentence variable
   MessageContainer.append("me: "+sentence +"\n");// show the message the client send  on his Jtextarea
   sentence= Name.getText()+": "+sentence;// send the message to other clients with his name
      sendData = sentence.getBytes();   // converting the message to bytes
      if(All.isSelected()){// if radio button is pressed on All 
          
      
      for(int i=0;i<2;i++){
            DatagramPacket sendPacket = 
         new DatagramPacket(sendData, sendData.length, IPAddress, Integer.parseInt(destination[i]));//storing data in datagramPacket object to other clients 
  
      clientSocket.send(sendPacket); //send data to other clients
  
      }
      }
      else if(First.isSelected()){// if first radio button is pressed
          
            DatagramPacket sendPacket = 
         new DatagramPacket(sendData, sendData.length, IPAddress, Integer.parseInt(destination[0])); //storing data in datagramPacket object to first client
  
      clientSocket.send(sendPacket); //send data to other clients
      }
      else{
            DatagramPacket sendPacket = 
         new DatagramPacket(sendData, sendData.length, IPAddress, Integer.parseInt(destination[1])); //storing data in datagramPacket object to second client 
  
      clientSocket.send(sendPacket); //send data to other clients
      }
      clientSocket.close();//close socket
      
            } catch (SocketException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnknownHostException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Chat.class.getName()).log(Level.SEVERE, null, ex);
            }
  
            
               

        }}).start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JRadioButton All;
    private javax.swing.JTextField Dest;
    private static javax.swing.JRadioButton First;
    private static javax.swing.JTextField IP;
    public static javax.swing.JTextArea MessageContainer;
    private static javax.swing.JTextField Name;
    private static javax.swing.JRadioButton Second;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField message;
    private javax.swing.JTextField rec;
    private javax.swing.JButton send;
    private javax.swing.JButton set;
    // End of variables declaration//GEN-END:variables
}
